config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'users#index'
  get '/register', to: 'users#new'
  post '/users', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get 'my_post',to: 'users#my_post'

  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

  has_many_attached :images
  belongs_to :user

  validates :text, presence: { message: 'Text Can\'t be empty' }
end

app/models/user.rb
# frozen_string_literal: true

# This is User Model
class User < ApplicationRecord
  before_create :downcase_email
  has_many :posts
  has_secure_password 
  validates :name, presence: { message: 'Name Can\'t be empty' }
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message: 'Invalid Email' },
                    uniqueness: { message: 'Already exist', case_sensitive: false },
                    presence: { message: 'Email can\'t be empty' }
  validates :password_digest, presence: { message: 'Password Can\'t be empty' }
  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  rescue_from ActiveRecord::RecordNotFound, with: :not_found_method
  helper_method :current_user

  def not_found_method
    render file: Rails.public_path.join('404.html'), status: :not_found, layout: false
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to login_path, flash: { success: 'Please Sign In' } unless current_user
  end
  def logged_in
    redirect_to root_path, flash: { error: 'Already Signed In' } if current_user
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authorize
  def new
    @post = Post.new

  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to root_path, flash: {success: 'Posts succesfully created'}
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to root_path flash: {success: "post updated succesfully"}
    else
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      redirect_to root_path flash: {success: "post deleted succesfully"}
    else  
      redirect_to root_path flash: {error: "unable to process your request"}
    end
  end

  private

  def post_params
    params.require(:post).permit(:text,images: [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :authorize, only: [:destroy]
  before_action :logged_in, except: [:destroy]

  def new; end

  def create
    user = User.find_by_email(params[:email]&.downcase)
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, flash: { success: 'Successfully logged in' }
    else
      redirect_to login_path, flash: { error: 'Invalid email id or password' }
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path, flash: { success: 'You are successfully logged out' }
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# This is Users Controller
class UsersController < ApplicationController
  before_action :authorize,only: :my_post
  def index
    # @users = User.all
    @posts = Post.all
  end
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, flash: { success: 'Signup Sucessfull' }
    else
      render :new
    end
  end

  def my_post 
    @posts = current_user.posts.order(created_at: :desc)
  end
  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_errors(object, field_name)
    return unless object.errors.any?
    return if object.errors.messages[field_name].blank?

    object.errors.messages[field_name].join(', ')
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render partial: 'shared/nav' %>
  <%= render partial: 'shared/flash' %>
    <%= yield %>
    <script src="https://kit.fontawesome.com/bb970ecffe.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="mx-auto w-25">
  <h1 class="mt-2"><%=label%></h1>
  <%= form_for :post, url: url,method: method do |f| %>
    <div class="mb-3">
      <%= f.label :content,class:"form-label required" %>
      <%= f.text_area :text,class:"form-control",placeholder:"Enter Your name" %>
      <p class='error'><%= show_errors(@post, :text) %></p>
    </div>
    <div class="mb-3">
      <%= f.label :images, "Image (PNG, JPG, JPEG, max 1MB)" %>
      <%= f.file_field :images, multiple: true%>
      <p class='error'><%= show_errors(@post, :images) %></p>
    </div>
    <%= f.submit "Submit" ,class:"btn btn-primary w-100 d-block text-center"%>
  <% end %>
</div>

app/views/posts/edit.html.erb
<%= render partial: 'form',locals: {label:"Edit Post",method: :patch,url:post_path(@post)} %>

app/views/posts/new.html.erb
<%= render partial: 'form',locals: {label:"Create New Post",method: :post,url: '/posts'} %>

app/views/shared/_flash.html.erb
<div id="my-flash">
  <% flash.each do |type,msg| %>
    <% if type=="error" %>
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <p class="text-center"><%=msg %></p>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% else %>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <p class="text-center"><%= msg %></p>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <%end%>
  <% end %>
</div>

app/views/shared/_nav.html.erb
<% unless controller_name == 'sessions' ||  (controller_name == 'users' && (action_name =='new' || action_name == 'create'))%>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <%= link_to 'Twitter', root_path, class: 'navbar-brand' %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <% if current_user %>
            <li class="nav-item">
              <strong class="nav-link"><%= current_user.name%></strong>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to 'Home', root_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Create Post', new_post_path, class: 'nav-link' %>
          </li>
          <% if current_user %>
            <li class="nav-item ml-auto">
              <%= link_to 'My Post', my_post_path, class: 'nav-link' %>
            </li>
            <li class="nav-item ml-auto">
              <%= link_to 'Log out', logout_path, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item ml-auto">
              <%= link_to 'Login/Signup', login_path, class: 'nav-link' %>
            </li>
          <% end %>
          <!-- Add more menu items as needed -->
        </ul>
      </div>
    </div>
  </nav>
<% end %>

app/views/users/_post.html.erb
<div class="container mt-4">
  <h2><%= label%></h2>
  <% @posts.each do |post| %>
    <div class="card mb-3">
      <% if post.images.present? %>
        <%= image_tag post.images.first,class:"card-img-top" ,alt:"card-thumbnail" %>
      <% end %>
      <div class="card-body">
        <p class="card-text"><%= post.text %></p>
        <p class="card-text"><small class="text-muted">Posted by <%= post.user.name %></small></p>
        <% if current_user&.id == post&.user_id%>
          <div class="btn-group">
            <%= link_to 'Edit', edit_post_path(post), class: 'btn btn-sm btn-primary' %>
            <%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<%= render partial: 'post',locals:{label: "All Posts"}%>

app/views/users/my_post.html.erb
<%= render partial: 'post',locals:{label: "My Post"}%>

app/views/users/new.html.erb
<div class="mx-auto w-25">
  <h1 class="mt-2">Signup!</h1>
  <%= form_for :user, url: '/users' do |f| %>
    <div class="mb-3">
      <%= f.label :name,class:"form-label required" %>
      <%= f.text_field :name,class:"form-control",placeholder:"Enter Your name" %>
      <p class='error'><%= show_errors(@user, :name) %></p>
    </div>
    <div class="mb-3">
      <%= f.label :email,class:"form-label required" %>
      <%= f.text_field :email,class:"form-control",placeholder:"Enter Your email" %>
      <p class='error'><%= show_errors(@user, :email) %></p>
    </div>
    <div class="mb-3">
      <%= f.label :Password,class:"form-label required" %>
      <%= f.password_field :password,class:"form-control",placeholder:"Enter Your password" %>
      <p class='error'><%= show_errors(@user, :password) %></p>
    </div>
    <div class="mb-3">
      <%= f.label :password_confirmation,class:"form-label required" %>
      <%= f.password_field :password_confirmation,class:"form-control",placeholder:"Enter same password as above" %>
      <p class='error'><%= show_errors(@user, :password_confirmation) %></p>
    </div>
    <%= f.submit "Submit" ,class:"btn btn-success w-100 d-block text-center mb-2"%>
  <% end %>
  <%= link_to 'Existing User! Login','/login',class:"d-block btn btn-primary mb-2 w-100 text-center" %>
  <%= link_to 'Home Page','/',class:"d-block btn btn-primary w-100 text-center" %>
</div>